version: "3"
services:
  app:
    build: .
    env_file:
      - aws-region.env
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    command: ["bash"]
