name: 'Terraform'

on:
  push:
    branches: [ '**' ]
    paths: [ '/terraform' ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - run: terraform fmt -check -diff -recursive
    - run: terraform init -backend=false
    - run: terraform validate
